# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 08da762cb0bf99066dd72812ae5761fcf9fdf977444f6b46474694bb0bf7441d5f034d551b57006a08f8fe5497453e3adaf0d1c661ee1d50b6b0ca56288984ac

test:
  secret_key_base: 80795986f8bd258606fba9ae5ef6cb0362f43fafafa715e13f7d7563e121d00f8249f3ccc1f233cc17322771cc617ab8ba132d96eae68c679afdfabb7e4e7393

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
